Update docker-ci.yml

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -40,16 +40,14 @@ jobs:
       - name: Launch Web Service
         run: docker compose up -d
 
-      - name: Wait for Web Service to Start
-        run: 
-          chmod +x wait-for-webserver.sh
-          ./wait-for-webserver.sh
+      - name: Wait for webserver
+        run: bash wait-for-webserver.sh
 
       - name: Run Selenium Tests
         run: cd selenium && mvn test
 
-      - name: Show Test Failure Details
-        if: failure()
-        run: |
-          echo "=== SUREFIRE REPORTS ==="
-          cat selenium/target/surefire-reports/*.txt || true
+      # - name: Show Test Failure Details
+      #   if: failure()
+      #   run: |
+      #     echo "=== SUREFIRE REPORTS ==="
+      #     cat selenium/target/surefire-reports/*.txt || true
